spring:
  profiles:
    active: aws
  config:
    import: classpath:/aws.yml

---

spring:
  profiles:
    group:
      "jongsu": "jongsudb, common"
      "heather": "heatherdb,common"
      "dev": "devdb,common"
      "aws": "awsdb,common"

---

spring:
  config:
    activate:
      on-profile: "devdb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://link:3306/petra?validationQuery="select 1"&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: password

---

spring:
  config:
    activate:
      on-profile: "heatherdb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/petra?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: Heather
    password: HeatherMySQL

---

spring:
  config:
    activate:
      on-profile: "jongsudb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/petra?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234

---

spring:
  config:
    activate:
      on-profile: "awsdb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://petra-db.cqlbbqbjndhk.ap-northeast-2.rds.amazonaws.com:3306/petra?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 12345678


---

spring:
  config:
    activate:
      on-profile: "common"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: none
    show-sql: true

---

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error