openapi: 3.0.1
info:
  title: PETRA API
  description: PETRA API description
  version: 0.1.0
servers:
- url: http://localhost:8080
tags: []
paths:
  /login:
    post:
      tags:
      - login
      summary: 로그인 후 쿠키 발급
      description: 로그인 후 쿠키를 발급받을 수 있습니다.
      operationId: LogIn and Get Cookie
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/login1607700006'
            examples:
              LogIn and Get Cookie:
                value: |-
                  {
                    "id" : "heather",
                    "name" : "한인주"
                  }
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/login-1664081379'
              examples:
                LogIn and Get Cookie:
                  value: |-
                    {
                      "code" : 2000,
                      "message" : "성공"
                    }
components:
  schemas:
    login1607700006:
      type: object
      properties:
        name:
          type: string
          description: 사용자 이름
        id:
          type: string
          description: 사용자 ID
    login-1664081379:
      type: object
      properties:
        code:
          type: number
          description: 응답코드
        message:
          type: string
          description: 응답메시지
